VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#------------------------------------------------------------------------------
# Common settings that all VMs share

    config.vm.synced_folder "shared", "/home/vagrant/shared"
    config.vm.box = "ubuntu/wily64"

#------------------------------------------------------------------------------

    config.vm.define "red" do |red|
        red.vm.synced_folder "shared", "/home/vagrant/shared"
        red.vm.box = "ubuntu/wily64"
        red.vm.hostname = 'red'

        red.vm.provider :virtualbox do |vb|
            # Force more aggressive time updates, needed for when host machine sleeps
            vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]

            # Set memory lower
            vb.memory = 1024
            vb.cpus = 2
        end

        red.vm.provision "ansible" do |ansible|
             ansible.groups = {
                 "vagrant_managed" => ["red"]
             }
            ansible.verbose = "vv"
            ansible.playbook = "example.yml"
        end
    end

end
